apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: prakashr1810/my-app:430745a8d7df33c34f1bee5ef26f5b0258e233a6
        ports:
        - containerPort: 80
